In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [8]:
folder = Path("/mnt/sdb/arafat/6mw/csv_raw2")

file_ids = {
    f.stem.split("_")[0][0] + "-" + f.stem.split("_")[0][1:].zfill(2)
    for f in folder.iterdir()
    if f.is_file()
}
print(len(file_ids))
file_ids

122

{'C-01',
 'C-02',
 'C-03',
 'C-04',
 'C-05',
 'C-06',
 'C-07',
 'C-08',
 'C-09',
 'C-10',
 'C-11',
 'C-12',
 'C-13',
 'C-14',
 'C-15',
 'C-16',
 'C-17',
 'C-18',
 'C-19',
 'C-20',
 'C-21',
 'C-22',
 'C-23',
 'C-24',
 'C-25',
 'C-26',
 'C-27',
 'C-28',
 'C-29',
 'C-30',
 'C-31',
 'C-32',
 'C-33',
 'C-34',
 'C-35',
 'C-36',
 'C-37',
 'C-39',
 'C-40',
 'C-41',
 'C-42',
 'C-43',
 'C-44',
 'C-45',
 'C-46',
 'C-47',
 'C-48',
 'C-49',
 'C-50',
 'C-51',
 'C-52',
 'C-53',
 'C-54',
 'C-55',
 'C-57',
 'C-58',
 'C-59',
 'C-60',
 'C-61',
 'C-62',
 'C-63',
 'C-64',
 'C-65',
 'C-66',
 'C-67',
 'C-68',
 'C-69',
 'C-70',
 'C-71',
 'C-72',
 'M-01',
 'M-02',
 'M-04',
 'M-05',
 'M-06',
 'M-07',
 'M-08',
 'M-09',
 'M-10',
 'M-11',
 'M-12',
 'M-13',
 'M-14',
 'M-15',
 'M-16',
 'M-17',
 'M-18',
 'M-20',
 'M-22',
 'M-23',
 'M-24',
 'M-25',
 'M-26',
 'M-29',
 'M-30',
 'M-32',
 'M-35',
 'M-36',
 'M-37',
 'M-38',
 'M-39',
 'M-40',
 'M-41',
 'M-43',
 'M-44',
 'M-45',
 'M-46',
 'M-47',
 'M-48',
 'M-49',
 'M-50',
 'M-51',
 'M-52',
 'M-53',
 'M-54',
 'M-55',
 'M-56',
 'M-57',
 'M-58',
 'M-60',
 'M-62',
 'M-63'}

In [9]:
demo_df = pd.read_excel("/mnt/sdb/arafat/6mw/SwayDemographics.xlsx")
demo_df

,ID,Grp,Sex,Age,Ethnicity,Race,Height,Weight,BMI,BMI Cat,...,MS Onset,MS Dur,BDI Rank,BDI Raw Score,MFIS Phys,MFIS Cog,MFIS Psych,MFIS Total,MS FSS,EDSS Total
0,M-01,MS,1,21,0.0,1,188.0,149.200,42.213671,4,...,11,10,3,19,3,8,2,13,10,1.5
1,M-02,MS,1,17,0.0,1,181.6,65.400,19.831066,2,...,14,3,1,1,0,0,0,0,9,1
2,M-03,MS,2,15,0.0,1,161.0,71.390,27.541376,3,...,7,8,1,7,18,23,1,42,28,1.5
3,M-04,MS,1,14,0.0,1,172.1,70.490,23.799387,3,...,13,1,1,3,14,6,1,21,24,2
4,M-05,MS,2,19,0.0,4,166.4,58.786,21.230844,2,...,17,2,0,0,1,0,0,1,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,C-81,Control,2,14,NaN,1,167.5,134.400,47.900000,4,...,.,.,2,12,16,7,4,27,16,.
146,C-82,Control,2,18,NaN,1,173.3,109.800,36.600000,4,...,.,.,1,6,0,0,0,0,11,.
147,C-83,Control,2,12,NaN,1,161.0,59.300,22.900000,3,...,.,.,0,0,3,3,0,6,21,.
148,C-84,Control,1,11,NaN,1,135.7,26.800,14.600000,2,...,.,.,1,2,5,2,0,7,11,.
149,C-85,Control,1,14,NaN,1,142.7,42.000,20.600000,2,...,.,.,1,9,7,11,0,18,15,.

In [10]:
filtered_demo_df = demo_df[demo_df["ID"].isin(file_ids)]
filtered_demo_df

,ID,Grp,Sex,Age,Ethnicity,Race,Height,Weight,BMI,BMI Cat,...,MS Onset,MS Dur,BDI Rank,BDI Raw Score,MFIS Phys,MFIS Cog,MFIS Psych,MFIS Total,MS FSS,EDSS Total
0,M-01,MS,1,21,0.0,1,188.00,149.200,42.213671,4,...,11,10,3,19,3,8,2,13,10,1.5
1,M-02,MS,1,17,0.0,1,181.60,65.400,19.831066,2,...,14,3,1,1,0,0,0,0,9,1
3,M-04,MS,1,14,0.0,1,172.10,70.490,23.799387,3,...,13,1,1,3,14,6,1,21,24,2
4,M-05,MS,2,19,0.0,4,166.40,58.786,21.230844,2,...,17,2,0,0,1,0,0,1,9,0
5,M-06,MS,2,12,0.0,1,150.90,51.170,22.477710,3,...,11,1,0,0,0,0,0,0,9,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,C-68,Control,1,12,NaN,1,166.37,68.600,24.784153,2,...,.,.,0,0,0,0,0,0,9,.
133,C-69,Control,1,14,NaN,1,175.60,61.700,20.000000,2,...,.,.,0,0,0,0,0,0,10,.
134,C-70,Control,2,18,NaN,1,168.00,57.900,20.500000,2,...,.,.,0,0,4,7,0,11,14,.
135,C-71,Control,1,18,NaN,5,173.00,71.500,23.900000,2,...,.,.,1,5,8,13,2,23,23,.
136,C-72,Control,1,12,NaN,1,173.00,67.600,23.000000,3,...,.,.,0,0,1,1,0,2,9,.

In [14]:
filtered_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122 entries, 0 to 136
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             122 non-null    object
 1   Grp            122 non-null    object
 2   Sex            122 non-null    int64
 3   Age            122 non-null    int64
 4   Ethnicity      52 non-null     float64
 5   Race           122 non-null    int64
 6   Height         122 non-null    float64
 7   Weight         122 non-null    float64
 8   BMI            122 non-null    float64
 9   BMI Cat        122 non-null    int64
 10  Waist          122 non-null    object
 11  MS Onset       122 non-null    object
 12  MS Dur         122 non-null    object
 13  BDI Rank       122 non-null    int64
 14  BDI Raw Score  122 non-null    int64
 15  MFIS Phys      122 non-null    int64
 16  MFIS Cog       122 non-null    int64
 17  MFIS Psych     122 non-null    int64
 18  MFIS Total     122 non-null    int64
 19  MS FSS         122 non-null    object
 20  EDSS Total     122 non-null    object
dtypes: float64(4), int64(10), object(7)
memory usage: 21.0+ KB

In [17]:
ms_group = filtered_demo_df[filtered_demo_df['Grp'] == 'MS']
ms_group['MS Dur'] = ms_group['MS Dur'].astype(int)
ms_group.describe()

/tmp/ipykernel_2096116/894470472.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ms_group['MS Dur'] = ms_group['MS Dur'].astype(int)

,Sex,Age,Ethnicity,Race,Height,Weight,BMI,BMI Cat,MS Dur,BDI Rank,BDI Raw Score,MFIS Phys,MFIS Cog,MFIS Psych,MFIS Total
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,1.750000,16.576923,0.076923,1.923077,167.307115,80.516269,28.422467,3.057692,2.307692,1.480769,8.288462,9.519231,11.173077,1.480769,22.173077
std,0.437237,2.546402,0.269069,1.439583,10.409711,25.091259,6.847987,0.802287,2.218801,1.275568,8.621306,7.790115,10.060057,1.552864,18.097472
min,1.000000,11.000000,0.000000,1.000000,146.000000,49.800000,18.425773,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.750000,15.000000,0.000000,1.000000,160.000000,62.250000,23.763428,2.000000,1.000000,1.000000,2.000000,3.000000,2.750000,0.000000,9.500000
50%,2.000000,17.000000,0.000000,1.000000,166.450000,71.650000,26.590000,3.000000,1.000000,1.000000,5.000000,8.000000,8.000000,1.000000,18.000000
75%,2.000000,18.000000,0.000000,4.000000,173.475000,89.650000,32.875000,4.000000,3.000000,2.000000,12.000000,15.250000,19.250000,2.000000,33.500000
max,2.000000,24.000000,1.000000,5.000000,189.000000,149.200000,47.100000,4.000000,10.000000,5.000000,34.000000,27.000000,39.000000,6.000000,63.000000

In [19]:
ms_group['Sex'].value_counts()

Sex
2    39
1    13
Name: count, dtype: int64

In [21]:
ms_group['Race'].value_counts()

Race
1    36
4    13
5     2
2     1
Name: count, dtype: int64

In [13]:
c_group = filtered_demo_df[filtered_demo_df['Grp'] == 'Control']
c_group.describe()

,Sex,Age,Ethnicity,Race,Height,Weight,BMI,BMI Cat,BDI Rank,BDI Raw Score,MFIS Phys,MFIS Cog,MFIS Psych,MFIS Total
count,70.000000,70.000000,0.0,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000
mean,1.642857,17.914286,NaN,1.885714,169.018000,66.210143,23.040249,2.300000,0.900000,4.071429,4.614286,6.171429,0.885714,11.671429
std,0.482617,3.202096,NaN,1.469919,9.475473,14.187038,3.839086,0.573573,0.782971,5.769288,4.935212,6.197174,1.148949,11.395043
min,1.000000,11.000000,NaN,1.000000,152.200000,38.600000,16.100000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,15.000000,NaN,1.000000,162.050000,57.750000,20.701950,2.000000,0.000000,0.000000,1.000000,2.000000,0.000000,2.250000
50%,2.000000,18.000000,NaN,1.000000,167.820000,62.450000,22.644567,2.000000,1.000000,2.000000,3.000000,4.000000,0.000000,8.500000
75%,2.000000,20.750000,NaN,3.000000,174.712500,72.100000,24.675000,3.000000,1.000000,5.000000,8.000000,10.000000,1.750000,17.500000
max,2.000000,25.000000,NaN,5.000000,192.000000,114.100000,37.900000,4.000000,4.000000,30.000000,19.000000,30.000000,5.000000,52.000000

In [20]:
c_group['Sex'].value_counts()

Sex
2    45
1    25
Name: count, dtype: int64

In [22]:
c_group['Race'].value_counts()

Race
1    49
5     8
4     6
3     5
2     2
Name: count, dtype: int64